spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
  datasource:
    url: ${datasource-url} #Url of MySQL in azure
    username: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none #turn off DDL auto generation
ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions} # environment variable with a default value
    api-key: ${AI_OPENAI_API_KEY:YOUR_API_KEY} # environment variable with a default value